const STATUS_POSTS = {
  ACTIVE: 'ACTIVE',
  TAKEDOWN: 'TAKEDOWN',
  FLAG: 'FLAG'
}

const ALGOLIA_INDEX_POSTS = "posts"
const ALGOLIA_INDEX_USERS = "users"
const ALGOLIA_INDEX_ROOMS = "rooms"
const ALGOLIA_INDEX_REPORT_POSTS = "report_posts"

module.exports = {
  STATUS_POSTS,
  ALGOLIA_INDEX_POSTS,
  ALGOLIA_INDEX_USERS,
  ALGOLIA_INDEX_ROOMS,
  ALGOLIA_INDEX_REPORT_POSTS
}