const STATUS_POSTS = {
  ACTIVE: 'ACTIVE',
  TAKEDOWN: 'TAKEDOWN',
  FLAG: 'FLAG'
}

const ALGOLIA_INDEX_POSTS = "posts"
const ALGOLIA_INDEX_USERS = "users"

module.exports = {
  STATUS_POSTS,
  ALGOLIA_INDEX_POSTS,
  ALGOLIA_INDEX_USERS
}